# Generated by Django 5.2.7 on 2025-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
                ('lenght', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('characte_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
