# Generated by Django 5.2.7 on 2025-10-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyzedstring',
            old_name='characte_frequency_map',
            new_name='character_frequency_map',
        ),
        migrations.RenameField(
            model_name='analyzedstring',
            old_name='lenght',
            new_name='length',
        ),
    ]
